### ISSUE TITLE
Error: write EPROTO?

### ISSUE THREAD

**Issue by reivax** [sreid/aws-iot-raspberry-pi-how-to#1]
thanks for writing such a detailed example. I updated the  AWS package as you explained but I'm getting the following error: (tried as well with latest AWS) - seems like a certificate issue if I got it correctly but i fI run openssl in the command line it seems my certs are correct:
openssl s_client -connect iot.us-east-1.amazonaws.com:443 -CAfile ./certs/root-CA.crt -cert ./certs/bd4b7d63bb-certificate.pem -key ./certs/bd4b7d63bb-private-key.pem
I get CONNECTED and Verify return code: 0 (ok) ---- read:errno=104

/home/bananapi/awsTest/node_modules/aws-iot-device-sdk/device/index.js:68
        throw new Error(error);
        ^

Error: Error: write EPROTO
    at MqttClient.<anonymous> (/home/bananapi/awsTest/node_modules/aws-iot-device-sdk/device/index.js:68:15)
    at emitOne (events.js:82:20)
    at MqttClient.emit (events.js:169:7)
    at TLSSocket.handleTLSerrors (/home/bananapi/awsTest/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/connect/tls.js:39:18)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)

Any idea what I could have done wrong? thanks in advance for any suggestions you may have...

**Comment by sreid** [comment]
Hi reivax,

From the looks of the error message, I think this might be something related to the AWS SDK directly, or possibly a underlying connection issue. You could try opening a issue on their GitHub page: https://github.com/aws/aws-iot-device-sdk-js/issues

You might try a manual connection to MQTT as described on this page, to help rule out any sort of connection/port/proxy problem:
https://docs.aws.amazon.com/iot/latest/developerguide/verify-pub-sub.html

Sorry to not be more help!

**Comment by sreid** [comment]
(closing this issue)
