### ISSUE TITLE
install aws-iot-device-sdk-js error

### ISSUE THREAD

**Issue by horizontracy** [sreid/aws-iot-raspberry-pi-how-to#2]
Hi,
I met a issue when installing your js sdk. Following is the full log.

```
pi@raspberrypi:~/dev/aws_iot $ npm install https://github.com/aws/aws-iot-device-sdk-js -g
\
> bufferutil@1.2.1 install /home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate/build'

> aws-iot-device-sdk@1.0.7 postinstall /home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk
> node ./node_modules/gulp/bin/gulp.js --verbose

module.js:338
    throw err;
    ^

Error: Cannot find module '/home/pi/.nvm/v4.0.0/lib/node_modules/aws-iot-device-sdk/node_modules/gulp/bin/gulp.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/home/pi/.nvm/v4.0.0/bin/node" "/home/pi/.nvm/v4.0.0/bin/npm" "install" "https://github.com/aws/aws-iot-device-sdk-js" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! aws-iot-device-sdk@1.0.7 postinstall: `node ./node_modules/gulp/bin/gulp.js --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-iot-device-sdk@1.0.7 postinstall script 'node ./node_modules/gulp/bin/gulp.js --verbose'.
npm ERR! This is most likely a problem with the aws-iot-device-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/gulp/bin/gulp.js --verbose
npm ERR! You can get their info via:
npm ERR!     npm owner ls aws-iot-device-sdk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dev/aws_iot/npm-debug.log
```

Besides, I installed my rpi with node. Here is the info.

```
pi@raspberrypi:~/dev/aws_iot $ node -v
v4.0.0
pi@raspberrypi:~/dev/aws_iot $ npm -v
2.14.2
```

Could u please give any suggestions? Many Thanks.

**Comment by h05558** [comment]
I am encountering the same issue...
